#ifndef INC_APP_NAV_CONFIG_H_
#define INC_APP_NAV_CONFIG_H_

#include "app_nav_types.h"
#include "pid_controller.h"

/*
 * Default navigation configuration for the portable navigation core.
 *
 * The current firmware still owns the live navigation variables in app_core.c.
 * These defaults are introduced as the future extraction boundary so that the
 * same navigation core can later be copied to the Qt simulator.
 */

#define APP_NAV_DEFAULT_RIGHT_MOTOR_BASE_SPEED 3575U
#define APP_NAV_DEFAULT_LEFT_MOTOR_BASE_SPEED 4550U
#define APP_NAV_DEFAULT_FASTER_SMOOTH_TURN_SPEED 6000U
#define APP_NAV_DEFAULT_SLOWER_SMOOTH_TURN_SPEED 2500U

#define APP_NAV_DEFAULT_WALL_THRESHOLD_FRONT_MM 70U
#define APP_NAV_DEFAULT_WALL_THRESHOLD_BRAKING_START_MM 40U
#define APP_NAV_DEFAULT_WALL_THRESHOLD_DIAGONAL_MM 130U
#define APP_NAV_DEFAULT_WALL_THRESHOLD_SIDE_MM 100U
#define APP_NAV_DEFAULT_WALL_HYSTERESIS_MM 15U
#define APP_NAV_DEFAULT_AFTER_TURN_WALL_THRESHOLD_MM 80U
#define APP_NAV_DEFAULT_WALL_TARGET_MM 55U
#define APP_NAV_DEFAULT_WALL_BRAKING_TARGET_MM 30U
#define APP_NAV_DEFAULT_APPROACH_FRONT_WALL_TARGET_MM 30U
#define APP_NAV_DEFAULT_TAPE_DETECTION_THRESHOLD_ADC 1500U
#define APP_NAV_DEFAULT_TAPE_HYSTERESIS_ADC 200U

#define APP_NAV_DEFAULT_TURN_TARGET_DPS 360U
#define APP_NAV_DEFAULT_PIVOT_TURN_TARGET_DPS 360U
#define APP_NAV_DEFAULT_SMOOTH_TURN_COMPLETION_DEAD_ZONE_DEG 1U
#define APP_NAV_DEFAULT_SMOOTH_REAR_TAPE_MIN_YAW_DEG 45U
#define APP_NAV_DEFAULT_SMOOTH_POST_YAW_SEEK_TIMEOUT_TICKS 150U

#define APP_NAV_DEFAULT_ADVANCE_PID_KP_Q16 HUNDREDTHS_TO_FIXED(80)
#define APP_NAV_DEFAULT_ADVANCE_PID_KI_Q16 HUNDREDTHS_TO_FIXED(0)
#define APP_NAV_DEFAULT_ADVANCE_PID_KD_Q16 HUNDREDTHS_TO_FIXED(20)
#define APP_NAV_DEFAULT_ADVANCE_PID_OUTPUT_LIMIT_PWM 4000
#define APP_NAV_DEFAULT_SMOOTH_TURN_PID_KP_Q16 HUNDREDTHS_TO_FIXED(2000)
#define APP_NAV_DEFAULT_SMOOTH_TURN_PID_KI_Q16 HUNDREDTHS_TO_FIXED(500)
#define APP_NAV_DEFAULT_SMOOTH_TURN_PID_KD_Q16 HUNDREDTHS_TO_FIXED(200)
#define APP_NAV_DEFAULT_SMOOTH_TURN_PID_OUTPUT_LIMIT_PWM 6500
#define APP_NAV_DEFAULT_PIVOT_TURN_PID_KP_Q16 HUNDREDTHS_TO_FIXED(8000)
#define APP_NAV_DEFAULT_PIVOT_TURN_PID_KI_Q16 HUNDREDTHS_TO_FIXED(0)
#define APP_NAV_DEFAULT_PIVOT_TURN_PID_KD_Q16 HUNDREDTHS_TO_FIXED(15000)
#define APP_NAV_DEFAULT_PIVOT_TURN_PID_OUTPUT_LIMIT_PWM 6500
#define APP_NAV_DEFAULT_BRAKING_PID_KP_Q16 HUNDREDTHS_TO_FIXED(1000)
#define APP_NAV_DEFAULT_BRAKING_PID_KI_Q16 HUNDREDTHS_TO_FIXED(10)
#define APP_NAV_DEFAULT_BRAKING_PID_KD_Q16 HUNDREDTHS_TO_FIXED(500)
#define APP_NAV_DEFAULT_BRAKING_PID_OUTPUT_LIMIT_PWM 4000
#define APP_NAV_DEFAULT_BRAKING_MIN_SPEED_PWM 2200

static inline AppNavConfig App_Nav_DefaultConfig(void)
{
    AppNavConfig cfg;

    cfg.right_motor_base_speed = APP_NAV_DEFAULT_RIGHT_MOTOR_BASE_SPEED;
    cfg.left_motor_base_speed = APP_NAV_DEFAULT_LEFT_MOTOR_BASE_SPEED;
    cfg.faster_motor_smooth_turn_speed = APP_NAV_DEFAULT_FASTER_SMOOTH_TURN_SPEED;
    cfg.slower_motor_smooth_turn_speed = APP_NAV_DEFAULT_SLOWER_SMOOTH_TURN_SPEED;

    cfg.wall_threshold_mm_front = APP_NAV_DEFAULT_WALL_THRESHOLD_FRONT_MM;
    cfg.wall_threshold_mm_braking_start = APP_NAV_DEFAULT_WALL_THRESHOLD_BRAKING_START_MM;
    cfg.wall_threshold_mm_diagonal = APP_NAV_DEFAULT_WALL_THRESHOLD_DIAGONAL_MM;
    cfg.wall_threshold_mm_side = APP_NAV_DEFAULT_WALL_THRESHOLD_SIDE_MM;
    cfg.wall_hysteresis_mm = APP_NAV_DEFAULT_WALL_HYSTERESIS_MM;
    cfg.after_turn_wall_threshold_mm = APP_NAV_DEFAULT_AFTER_TURN_WALL_THRESHOLD_MM;
    cfg.wall_target_mm = APP_NAV_DEFAULT_WALL_TARGET_MM;
    cfg.wall_braking_target_mm = APP_NAV_DEFAULT_WALL_BRAKING_TARGET_MM;
    cfg.approach_front_wall_target_mm = APP_NAV_DEFAULT_APPROACH_FRONT_WALL_TARGET_MM;
    cfg.tape_detection_threshold_adc = APP_NAV_DEFAULT_TAPE_DETECTION_THRESHOLD_ADC;
    cfg.tape_hysteresis_adc = APP_NAV_DEFAULT_TAPE_HYSTERESIS_ADC;

    cfg.turn_target_dps = APP_NAV_DEFAULT_TURN_TARGET_DPS;
    cfg.pivot_turn_target_dps = APP_NAV_DEFAULT_PIVOT_TURN_TARGET_DPS;
    cfg.smooth_turn_completion_dead_zone_deg = APP_NAV_DEFAULT_SMOOTH_TURN_COMPLETION_DEAD_ZONE_DEG;
    cfg.smooth_rear_tape_min_yaw_deg = APP_NAV_DEFAULT_SMOOTH_REAR_TAPE_MIN_YAW_DEG;
    cfg.smooth_post_yaw_seek_timeout_ticks = APP_NAV_DEFAULT_SMOOTH_POST_YAW_SEEK_TIMEOUT_TICKS;

    cfg.advance_pid_kp_q16 = APP_NAV_DEFAULT_ADVANCE_PID_KP_Q16;
    cfg.advance_pid_ki_q16 = APP_NAV_DEFAULT_ADVANCE_PID_KI_Q16;
    cfg.advance_pid_kd_q16 = APP_NAV_DEFAULT_ADVANCE_PID_KD_Q16;
    cfg.advance_pid_output_limit_pwm = APP_NAV_DEFAULT_ADVANCE_PID_OUTPUT_LIMIT_PWM;

    cfg.smooth_turn_pid_kp_q16 = APP_NAV_DEFAULT_SMOOTH_TURN_PID_KP_Q16;
    cfg.smooth_turn_pid_ki_q16 = APP_NAV_DEFAULT_SMOOTH_TURN_PID_KI_Q16;
    cfg.smooth_turn_pid_kd_q16 = APP_NAV_DEFAULT_SMOOTH_TURN_PID_KD_Q16;
    cfg.smooth_turn_pid_output_limit_pwm = APP_NAV_DEFAULT_SMOOTH_TURN_PID_OUTPUT_LIMIT_PWM;

    cfg.pivot_turn_pid_kp_q16 = APP_NAV_DEFAULT_PIVOT_TURN_PID_KP_Q16;
    cfg.pivot_turn_pid_ki_q16 = APP_NAV_DEFAULT_PIVOT_TURN_PID_KI_Q16;
    cfg.pivot_turn_pid_kd_q16 = APP_NAV_DEFAULT_PIVOT_TURN_PID_KD_Q16;
    cfg.pivot_turn_pid_output_limit_pwm = APP_NAV_DEFAULT_PIVOT_TURN_PID_OUTPUT_LIMIT_PWM;

    cfg.braking_pid_kp_q16 = APP_NAV_DEFAULT_BRAKING_PID_KP_Q16;
    cfg.braking_pid_ki_q16 = APP_NAV_DEFAULT_BRAKING_PID_KI_Q16;
    cfg.braking_pid_kd_q16 = APP_NAV_DEFAULT_BRAKING_PID_KD_Q16;
    cfg.braking_pid_output_limit_pwm = APP_NAV_DEFAULT_BRAKING_PID_OUTPUT_LIMIT_PWM;
    cfg.braking_min_speed_pwm = APP_NAV_DEFAULT_BRAKING_MIN_SPEED_PWM;

    return cfg;
}

#endif /* INC_APP_NAV_CONFIG_H_ */
